### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by mosaichaoyan** [geoschem/GEOS_FP#1]
Hi GEOS-Chem Team,

I have successfully tried CH4 emission analysis by implementing Yuzhong Zhang's 2020 paper (inverse modeling) using 2019 data. Right now I am trying to do it using 2022 data. Since the operational GEOS-FP data for GEOS-Chem is not updated yet, I want to use this GEOS_FP repo to process native GEOS-FP data. 

I used the tutorial AMI image ami-0983d1d6b06e4dd3f, and tried to follow instructions on [http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-FP_implementation_details#Top-level_directory](url). When trying to run 'make all' under GEOS_FP/Code directory, the following error shows up. Any thoughts or suggestions would be greatly appreciated!
<img width="432" alt="Screen Shot 2022-02-28 at 1 11 52 PM" src="https://user-images.githubusercontent.com/62110889/156035728-a81da1f1-567d-4df7-8dcb-b70f70d2a1a5.png">

<img width="448" alt="Screen Shot 2022-02-28 at 1 13 57 PM" src="https://user-images.githubusercontent.com/62110889/156036064-44058eb4-0eb1-43f0-a52e-c6c43fecd612.png">

**Comment by LiamBindle** [comment]
Hi @mosaichaoyan, this repository isn't supported, partly because it's legacy code with compilation and runtime issues. Starting in 13.4, the necessary metfield preprocessing for GC-Classic can be achieve with a couple NCO commands. I shared instructions with Hao on how you can do this, and the NCO route would be my recommendation.

**Comment by yantosca** [comment]
Closing issue for now.  We are going to archive this repo.
